# 1. Basics of Python

## 1.1 Elementary Data Types

| &nbsp;  |      Data Type    |   Example   |
|:--------|:-----------------:|:------------|
|Number   | Integer           | x = 4       |
| &nbsp;  | Long integer      | x = 15L     |
| &nbsp;  | Floating point    | x = 3.142   |
| &nbsp;  | Boolean           | x = True    |
|Text     | Character         | x = 'c'     |
| &nbsp;  | String            | x = \"this\" or x = 'this' |

In [1]:
x = 4              # integer
print(x, type(x))

y = True           # boolean (True, False)
print(y, type(y))

z = 3.7            # floating point
print(z, type(z))

s = "This is a string"    # string
print(s, type(s))

4 <class 'int'>
True <class 'bool'>
3.7 <class 'float'>
This is a string <class 'str'>


The following are some of the arithmetic operations available for manipulating integers and floating point numbers

In [2]:
x = 4            # integer
x1 = x + 4       # addition 
x2 = x * 3       # multiplication
x += 2           # equivalent to x = x + 2
x3 = x       
x *= 3           # equivalent to x = x * 3
x4 = x      
x5 = x % 4       # modulo (remainder) operator

z = 3.7          # floating point number
z1 = z - 2       # subtraction
z2 = z / 3       # division
z3 = z // 3      # integer division
z4 = z ** 2      # square of z 
z5 = z4 ** 0.5   # square root
z6 = pow(z,2)    # equivalent to square of z
z7 = round(z)    # rounding z to its nearest integer 
z8 = int(z)      # type casting float to int

print(x,x1,x2,x3,x4,x5)
print(z,z1,z2,z3,z4)
print(z5,z6,z7,z8)

18 8 12 6 18 2
3.7 1.7000000000000002 1.2333333333333334 1.0 13.690000000000001
3.7 13.690000000000001 4 3


The following are some of the functions provided by the math module for integers and floating point numbers

In [3]:
import math

x = 4
print(math.sqrt(x))      # sqrt(4) = 2
print(math.pow(x,2))     # 4**2 = 16
print(math.exp(x))       # exp(4) = 54.6
print(math.log(x,2))     # log based 2  (default is natural logarithm)
print(math.fabs(-4))     # absolute value
print(math.factorial(x)) # 4! = 4 x 3 x 2 x 1 = 24

z = 0.2
print(math.ceil(z))      # ceiling function
print(math.floor(z))     # floor function
print(math.trunc(z))     # truncate function

z = 3*math.pi            # math.pi = 3.141592653589793 
print(math.sin(z))       # sine function
print(math.tanh(z))      # arctan function

x = math.nan             # not a number
print(math.isnan(x))

x = math.inf             # infinity
print(math.isinf(x))

2.0
16.0
54.598150033144236
2.0
4.0
24
1
0
0
3.6739403974420594e-16
0.9999999869751758
True
True


The following are some of the logical operations available for booleans

In [4]:
y1 = True
y2 = False

print(y1 and y2)       # logical AND
print(y1 or y2)        # logical OR
print(y1 and not y2)   # logical NOT

False
True
True


The following are some of the operations and functions for manipulating strings

In [5]:
s1 = "This"

print(s1[1:])                    # print last three characters 
print(len(s1))                               # get the string length
print("Length of string is " + str(len(s1))) # type casting int to str
print(s1.upper())                            # convert to upper case
print(s1.lower())                            # convert to lower case

s2 = "This is a string"
words = s2.split(' ')             # split the string into words
print(words[0])
print(s2.replace('a','another'))  # replace "a" with "another"
print(s2.replace('is','at'))      # replace "is" with "at"
print(s2.find("a"))               # find the position of "a" in s2
print(s1 in s2)                   # check if s1 is a substring of s2

print(s1 == 'This')               # equality comparison
print(s1 < 'That')                # inequality comparison
print(s2 + " too")                # string concatenation
print((s1 + " ")* 3)              # replicate the string 3 times

his
4
Length of string is 4
THIS
this
This
This is another string
That at a string
8
True
True
False
This is a string too
This This This 


## 1.2 Compound Data Types

### 1.2.1 Python List [ ]

List is an **ordered sequence** of items. It is one of the most used datatype in Python and is very flexible. All the items in a list do not need to be of the same type.

Declaring a list is pretty straight forward. Items separated by commas are enclosed within brackets **[ ]**.

We can use the slicing operator **[ ]** to extract an item or a range of items from a list. The index starts from 0 in Python.

In [6]:
x = [6, 99, 77, 'Apple']
print(x, "is of type", type(x))

[6, 99, 77, 'Apple'] is of type <class 'list'>


In [7]:
a = [5, 10, 15, 20, 25, 30, 35, 40]  # Total elemnets is 8
#   [0   1   2   3   4   5   6   7]  ⬅ Index forward
#   [-8 -7  -6  -5  -4  -3  -2  -1]  ➡ Index backward

# index '0' is element '1' = 5,
# index '1' is element '2' = 10,
# index '2' is element '3' = 15,
# .
# .
# .
# index '7' is element '8' = 40,

a[1] # To access the elements in the list
    
# a[2] = 15
print("a[2] = ", a[2])

# a[0:3] = [5, 10, 15]
print("a[0:3] = ", a[0:3])  # [0:3] means elements from 0 uptil 2 index (not include last element)
                            # [0:3] means from index 0 to 3 - 1 
                            # [0:3] means from index 0 to 2
    
# a[5:] = [30, 35, 40]  # [5:] means all the elements from 5 till end
print("a[5:] = ", a[5:])

a[2] =  15
a[0:3] =  [5, 10, 15]
a[5:] =  [30, 35, 40]


In [8]:
a[1:-2]

[10, 15, 20, 25, 30]

In [9]:
a[5:9]

[30, 35, 40]

In [10]:
a[:5]

[5, 10, 15, 20, 25]

Lists are **mutable**, meaning, the value of elements of a list can be altered.

In [11]:
# Change the element of the List
a = [1, 2, 3]
#   [0  1  2] ➡ Index forward

a[2] = 4  # Change my third element from '3' to '4' # [2] is the index number
print(a)

[1, 2, 4]


## 1.3 Python Operators

Python can be used like a calculator. Simply type in expressions to get them evaluated.

**What are operators in python?**

Operators are special **symbols** in Python that carry out **arithmetic** or **logical computation**. The value that the operator operates on is called the **operand**.

For example:

'6+3'

9
Here, **+** is the operator that performs addition. 2 and 3 are the operands and 5 is the output of the **operation**.

In [12]:
6+3

9

### 1.3.1 Arithmatic Operators

Arithmetic operators are used to perform mathematical operations like addition, subtraction, multiplication etc.

| **Symbol** | **Task Performed**     |                                   **Meaning**                                   |              **Example**              |
|:----------:|------------------------|:-------------------------------------------------------------------------------:|:-------------------------------------:|
|      +     | Addition               |                          add two operands or unary plus                         |          **x + y** or +**2**          |
|      -     | Subtraction            |               substract right operand from the left or unary minus              |          **x - y** or **-2**          |
|      *     | Multiplication         |                              Multiply two operands                              |               **x * y**               |
|      /     | Division               |         Divide left operand by the right one (always results into float)        |               **x / y**               |
|      %     | Modulus (remainder)    |              remainder of the division of left operand by the right             |    **x % y** (remainder of **x/y**)   |
|     //     | Integer/Floor division | division that results into whole number adjusted to the left in the number line |               **x // y**              |
|     **     | Exponentiation (power) |                    left operand raised to the power of right                    | **x ** y** (**x** to the power **y**) |

As expected these operations generally promote to the most general type of any of the numbers involved i.e. int -> float -> complex.

In [13]:
print('Addition: ', 1 + 2)
print('Subtraction: ', 2 - 1)
print('Multiplication: ', 2 * 3)
print ('Division: ', 4 / 2)                         # Division in python gives floating number
print('Division: ', 6 / 2)
print('Division: ', 7 / 2)
print('Division without the remainder: ', 7 // 2)   # gives without the floating number or without the remaining
print('Modulus: ', 3 % 2)                           # Gives the remainder
print ('Division without the remainder: ',7 // 3)
print('Exponential: ', 3 ** 2)                      # it means 3 * 3

Addition:  3
Subtraction:  1
Multiplication:  6
Division:  2.0
Division:  3.0
Division:  3.5
Division without the remainder:  3
Modulus:  1
Division without the remainder:  2
Exponential:  9


In [14]:
x = 16
y = 3

print('x + y =',x+y) # 19
print('x - y =',x-y) # 13
print('x * y =',x*y) # 48
print('x / y =',x/y) # 5.333
print('x // y =',x//y) # 519

x + y = 19
x - y = 13
x * y = 48
x / y = 5.333333333333333
x // y = 5


### 1.3.2 Comparison/Relational operators

Comparison operators are used to **compare values**. It either returns **True** or **False** according to the **condition**.

| **Symbol** | **Task Performed**       | **Meaning**                                                | **Example** |
|:----------:|--------------------------|------------------------------------------------------------|:-----------:|
|      >     | greater than             | True if left operand is greater than the right             |  **x > y**  |
|      <     | less than                | True if left operand is less than the right                |  **x < y**  |
|     ==     | equal to                 | True if both operands are equal                            |  **x == y** |
|     !=     | not equal to             | True if both operands are not equal                        |  **x != y** |
|     >=     | greater than or equal to | True if left operand is greater than or equal to the right |  **x >= y** |
|     <=     | less than or equal to    | True if left operand is less than or equal to the right    |  **x <= y** |

[Caution] Note the difference between **==** (equality test) and **=** (assignment)

In [15]:
print(6 > 3)                           # True, because 3 is greater than 2
print(6 >= 3)                          # True, because 3 is greater than 2
print(6 < 3)                           # False,  because 3 is greater than 2
print(3 < 6)                           # True, because 2 is less than 3
print(3 <= 6)                          # True, because 2 is less than 3
print(6 == 3)                          # False, because 3 is not equal to 2
print(6 != 3)                          # True, because 3 is not equal to 2
print(len("apple") == len("avocado"))  # False
print(len("apple") != len("avocado"))  # True
print(len("apple") < len("avocado"))   # True
print(len("banana") != len("orange"))  # False
print(len("banana") == len("orange"))  # True
print(len("tomato") == len("potato"))  # True
print(len("python") > len("coding"))   # False

True
True
False
True
True
False
True
False
True
True
False
True
True
False


In [16]:
x = 30
y = 22

print('x > y is',x>y)   # False
print('x < y is',x<y)   # True
print('x >= y is',x>=y) # False
print('x <= y is',x<=y) # True

x > y is True
x < y is False
x >= y is True
x <= y is False


### 1.3.3 Logical/Boolean operators

Logical operators are the **and**, **or**, **not** operators.

| **Symbol** |                     **Meaning**                     | **Example** |
|:----------:|:---------------------------------------------------:|:-----------:|
|     and    |          True if both the operands are true         | **x and y** |
|     or     |        True if either of the operand is true        |  **x or y** |
|     not    | True if operand are false (complements the operand) |  **not x**  |

In [17]:
print('True == True: ', True == True)
print('True == False: ', True == False)
print('False == False:', False == False)
print('True and True: ', True and True)
print('True or False:', True or False)

True == True:  True
True == False:  False
False == False: True
True and True:  True
True or False: True


In [18]:
# Another way comparison 

print('1 is 1', 1 is 1)                  # True  - because the data values are the same
print('1 is not 2', 1 is not 2)          # True  - because 1 is not 2
print('A in Milaan', 'A' in 'Milaan')    # True  - A found in the string
print('B in Milaan', 'B' in 'Milaan')    # False - there is no uppercase B
print('python' in 'python is fun')       # True  - because coding for all has the word coding
print('a in an:', 'a' in 'an')           # True
print('27 is 3 ** 3:', 27 is 3**3)       # True

1 is 1 True
1 is not 2 True
A in Milaan False
B in Milaan False
True
a in an: True
27 is 3 ** 3: True


<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:4: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:9: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:4: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:9: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\andym\AppData\Local\Temp\ipykernel_5920\3673234325.py:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print('1 is 1', 1 is 1)                  # True  - because the data values are the same
C:\Users\andym\AppData\Local\Temp\ipykernel_5920\3673234325.py:4: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  print('1 is not 2', 1 is not 2)          # True  - because 1 is not 2
C:\Users\andym\AppData\Local\Temp\ipykernel_5920\3673234325.py:9: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print('27 is 3 ** 3:', 27 is 3**3)       # True


### 1.3.4 Assignment operators

Assignment operators are used in Python to **assign values** to **variables**.

**a = 5** is a simple assignment operator that assigns the value 5 on the right to the variable **a** on the left.

There are various compound operators in Python like **a += 5** that adds to the variable and later assigns the same. It is equivalent to **a = a + 5**.

| **Symbol** | **Example** | **Equivalent to** |
|:----------:|:-----------:|:-----------------:|
|      =     |  **x = 5**  |     **x = 5**     |
|     +=     |  **x += 5** |   **x = x + 5**   |
|     -=     |  **x -= 5** |   **x = x - 5**   |
|     *=     |  **x *= 5** |   **x = x * 5**   |
|     /=     |  **x /= 5** |   **x = x / 5**   |
|     %=     |  **x %= 5** |   **x = x % 5**   |
|     //=    | **x //= 5** |   **x = x // 5**  |
|     **=    | **x **= 5** |   **x = x ** 5**  |
|     &=     |  **x &= 5** |   **x = x & 5**   |
|     \|=    | **x \|= 5** |   **x = x \| 5**  |
|     ^=     |  **x ^= 5** |   **x = x ^ 5**   |
|     >>=    | **x >>= 5** |   **x = x >> 5**  |
|     <<=    | **x <<= 5** |   **x = x << 5**  |

The binary operators can be combined with assignment to modify a variable value. For example:

In [19]:
x = 1
x += 2 # add 2 to x
print("x is",x)
x <<= 2 # left shift by 2 (equivalent to x *= 4)
print('x is',x)
x **= 2 # x := x^2
print('x is',x)

x is 3
x is 12
x is 144


## 1.4 Control Flow Statements

Similar to other programming languages, the control flow statements in Python include **if-else**, **for**, and **while** statements. Examples on how to use these statements are shown below.

In [20]:
# using if-else statement

x = 10

if x % 2 == 0:
    print("x =", x, "is even")
else:
    print("x =", x, "is odd")

if x > 0:
    print("x =", x, "is positive")
elif x < 0:
    print("x =", x, "is negative")
else:
    print("x =", x, "is neither positive nor negative")

x = 10 is even
x = 10 is positive


In [21]:
# using for loop with a list

mylist = ['this', 'is', 'a', 'list']
for word in mylist:
    print(word.replace("is", "at"))
    
mylist2 = [len(word) for word in mylist]   # number of characters in each word
print(mylist2)

# using for loop with list of tuples

states = [('MI', 'Michigan', 'Lansing'),('CA', 'California', 'Sacramento'),
          ('TX', 'Texas', 'Austin')]

sorted_capitals = [state[2] for state in states]
sorted_capitals.sort()
print(sorted_capitals)

# using for loop with dictionary

fruits = {'apples': 3, 'oranges': 4, 'bananas': 2, 'cherries': 10}
fruitnames = [k for (k,v) in fruits.items()]
print(fruitnames)

that
at
a
latt
[4, 2, 1, 4]
['Austin', 'Lansing', 'Sacramento']
['apples', 'oranges', 'bananas', 'cherries']


In [22]:
# using while loop

mylist = list(range(-10,10))
print(mylist)

i = 0
while (mylist[i] < 0):
    i = i + 1
    
print("First non-negative number:", mylist[i])

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
First non-negative number: 0


## 1.5 User-Defined functions

You can create your own functions in Python, which can be named or unnamed. Unnamed functions are defined using the lambda keyword as shown in the previous example for sorting a list of tuples.

In [23]:
myfunc = lambda x: 3*x**2 - 2*x + 3      # example of an unnamed quadratic function

print(myfunc(2))

11


In [24]:
import math

# The following function will discard missing values from a list
def discard(inlist, sortFlag=False):    # default value for sortFlag is False 
    outlist = []
    for item in inlist:
        if not math.isnan(item):
            outlist.append(item)
            
    if sortFlag:
        outlist.sort()
    return outlist

mylist = [12, math.nan, 23, -11, 45, math.nan, 71]

print(discard(mylist,True))   

[-11, 12, 23, 45, 71]


## 1.6 File I/O

You can read and write data from a list or other objects to a file.
Below is the basic way to read and write data.
For data science, you can also use data reading modules from numpy or pandas package for reading excel files, but we will learn about these later

In [25]:
states = [('MI', 'Michigan', 'Lansing'),('CA', 'California', 'Sacramento'),
          ('TX', 'Texas', 'Austin'), ('MN', 'Minnesota', 'St Paul')]

with open('states.txt', 'w') as f:
    f.write('\n'.join('%s,%s,%s' % state for state in states))
    
with open('states.txt', 'r') as f:
    for line in f:
        fields = line.split(sep=',')    # split each line into its respective fields
        print('State=',fields[1],'(',fields[0],')','Capital:', fields[2])

State= Michigan ( MI ) Capital: Lansing

State= California ( CA ) Capital: Sacramento

State= Texas ( TX ) Capital: Austin

State= Minnesota ( MN ) Capital: St Paul


# 2. NumPy

**NumPy** (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The **NumPy** library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. **NumPy** can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

## 2.1. How to use NumPy

**import** means that you will use some library

To access NumPy and its functions **import** it in your Python code like this:

In [26]:
import numpy as np

We shorten the imported name to `np` for better readability of code using NumPy. This is a widely adopted convention that makes your code more readable for everyone working on it. We recommend to always use import numpy as `np`.

## 2.2 NumPy array

### 2.2.1 What’s the difference between a Python list and a NumPy array?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a **Python list** can contain different data types within a single list, all of the elements in a **NumPy array** should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

**Why use NumPy?**

**NumPy arrays** are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

### 2.2.2 What is an array?

An **array** is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array `dtype`.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The `rank` of the array is the number of dimensions. The `shape` of the array is a tuple of integers giving the size of the array along each dimension.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

For example:

In [27]:
a = np.array([1, 2, 3, 4, 5, 6])

or

In [28]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

We can access the elements in the array using **square brackets**. When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the **first element** in your array, you’ll be accessing **element “0”**.

In [29]:
print(a[0])

[1 2 3 4]


### 2.2.3. ndarray

'ndarray' is shorthand for N-dimensional array. An N-dimensional array is simply an array with any number of dimensions. (N=1,2,3,...)
The NumPy `ndarray` class is used to represent both matrices and vectors. A **vector** is an array with a single dimension (there’s no difference between row and column vectors), while a **matrix** refers to an array with two dimensions.

**What are the attributes of an array?**

An `array` is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its **shape**. The **shape** of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called **axes**. This means that if you have a 2D array that looks like this:

In [30]:
a = np.array([[0., 0., 0.],
              [1., 1., 1.]])
print(a)

[[0. 0. 0.]
 [1. 1. 1.]]


Your array has **2 axes**. The first axis has a length of 2 and the second axis has a length of 3.

Just like in other Python container objects, the contents of an array can be accessed and modified by **indexing** or **slicing** the array.

### 2.2.4. How to create a basic array

This section covers `np.array()`, `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`

To create a NumPy array, you can use the function `np.array()`.

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

In [31]:
import numpy as np

a = np.array([1, 2, 3])

You can visualize your array this way:

![](https://numpy.org/doc/stable/_images/np_array.png)

Besides creating an array from a sequence of elements, you can easily create an array filled with `0`s using `np.zeros()`:

In [32]:
np.zeros(2)

array([0., 0.])

Or an array filled with `1`s using `np.ones(2)`:

In [33]:
np.ones(2)

array([1., 1.])

You can create an array with a range of elements using `np.arange()` (0~N):

In [34]:
np.arange(4)

array([0, 1, 2, 3])

### 2.2.5. Adding, removing, and sorting elements

This section covers `np.sort()`, `np.concatenate()`

Sorting an element is simple with `np.sort()`. You can specify the axis, kind, and order when you call the function.

If you start with this array:

In [35]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

You can quickly sort the numbers in ascending order with:

In [36]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

If you start with these arrays:

In [37]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

You can concatenate them with `np.concatenate()`.

In [38]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### 2.2.6. How do you know the shape and size of an array?

This section covers `ndarray.ndim`, `ndarray.size`, `ndarray.shape`

`ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

`ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

`ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is `(2, 3)`.

For example, if you create this array:

In [39]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

To find the number of dimensions of the array, run:

In [40]:
array_example.ndim

3

To find the total number of elements in the array, run:

In [41]:
array_example.size

24

And to find the shape of your array, run:

In [42]:
array_example.shape

(3, 2, 4)

### 2.2.8. Indexing and slicing

You can **index** and **slice** NumPy arrays in the same ways you can slice Python lists.

In [43]:
data = np.array([1, 2, 3])

In [44]:
# Always remember. Indexing starts from 0
data[1]

2

In [45]:
data[0:2]

array([1, 2])

In [46]:
data[1:]

array([2, 3])

In [47]:
data[-2:]

array([2, 3])

You can visualize it this way:

![](https://numpy.org/doc/stable/_images/np_indexing.png)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain **conditions**, it’s straightforward with NumPy.

For example, if you start with this array:

In [48]:
a = np.array([[1 , 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.

In [49]:
print(a[a < 5])

[1 2 3 4]


## 2.3. Array operations

## 2.3.1. Basic array opeations

This section covers addition, subtraction, multiplication, division, and more

Once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called **“data”** and one called **“ones”**

![](https://numpy.org/doc/stable/_images/np_array_dataones.png)

In [50]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

You can add the arrays together with the plus sign.

In [51]:
data + ones

array([2, 3])

![](https://numpy.org/doc/stable/_images/np_data_plus_ones.png)

You can, of course, do more than just addition!

In [52]:
data - ones

array([0, 1])

In [53]:
data * data

array([1, 4])

In [54]:
data / data

array([1., 1.])

![](https://numpy.org/doc/stable/_images/np_sub_mult_divide.png)

Basic operations are simple with NumPy. If you want to find the sum of the elements in an array, you’d use `sum()`. This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [55]:
a = np.array([1, 2, 3, 4])
a.sum() # 1+2+3+4=10

10

### 2.3.3. More useful array operations

This section covers **maximum, minimum, sum, mean, product, standard deviation**

NumPy also performs aggregation functions. In addition to `min`, `max`, and `sum`, you can easily run `mean` to get the average, `prod` to get the result of multiplying the elements together, `std` to get the standard deviation, and more.

In [56]:
data = np.array([1.0, 2.0, 3.0])

In [57]:
data.max()

3.0

In [58]:
data.min()

1.0

In [59]:
data.sum()

6.0

![](https://numpy.org/doc/stable/_images/np_aggregation.png)

Let’s start with this array, called “a”

In [60]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

It’s very common to want to aggregate along a **row** or **column**. By default, every NumPy aggregation function will return the aggregate of the entire array. To find the sum or the minimum of the elements in your array, run:

In [61]:
a.sum()

4.8595784

In [62]:
a.min()

0.05093587

You can specify on which axis you want the aggregation function to be computed. For example, you can find the minimum value within each **column** by specifying `axis=0`.

In [63]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

# 3. Pandas

Pandas is a Python library used for working with data sets. It has functions for analyzing, cleaning, exploring, and manipulating data.

Pandas allows us to analyze big data and make conclusions based on statistical theories. Pandas can clean messy data sets, and make them readable and relevant. Relevant data is very important in data science.

When working with **tabular or structured data**, we can do following things easily:

- Import data
- Clean up messy data
- Explore data, gain insight into data
- Process and prepare your data for analysis
- Analyse your data (together with scikit-learn, statsmodels, ...)

## 3.1. How to Use Pandas

Do you remember how we used **numpy** library? We **imported** the numpy using `import numpy as np`. We will do simliar thing with Pandas.

To access **Pandas** and its functions import it in your Python code like this:

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

We shorten the imported name to `pd` for better readability of code using **Pandas**. This is a widely adopted convention that makes your code more readable for everyone working on it. We recommend to always use `import pandas as pd`.

## 3.2. Data structures in Pandas

We will learn about two data structures provided by Pandas, `Series` and `DataFrame`

### 3.2.1 Series

`Series` is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the **index**. 

You can think of each `Series` as **one column of excel sheet**.

The basic method to create a `Series` is to call:

In [ ]:
s = pd.Series([1, 3, 5, 4, 6, 8])
print(s)

Above, the fist column is index. Since we did not defined the index while creating a series `s`, `s` has a default index, which starts from 0.

The second column is the values in `s`. We gave the list ([1, 3, 5, 4, 6, 8]) as the input to create `s`, so the values in the list ([1, 3, 5, 4, 6, 8]) become the values.

Since every value in `s` are integers, the datatype of `s` becomes `int64`.

In [ ]:
s = pd.Series([1, 3.5, 5, 4, 6.2, 8])
print(s)

When there are both integers and floating points numbers inside the list given to `s`, the datatype of `s` becomes `float64`.

We can also define the index of `Series` like this:

In [ ]:
s = pd.Series([1, 3.5, 5, 4, 6.2, 8], index=['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

The `index` keyword in `pd.Series(,index=)` defines what the index of Series will be.

### 3.2.2. DataFrame

While `Series` is a one-dimensional labeled array, `DataFrame` is a two-dimensional data structure that holds data likea two-dimension array or a table with rows and columns.

Therefore, `DataFrame` is just like the each excel sheet. You will mostly use `DataFrame` when analyzing data.

You can create a `DataFrame` using `dictionary` like follows:

In [ ]:
df = pd.DataFrame({'Apples': [1,3,7,4],
                  'Bananas': [2,6,3,5]})

In [ ]:
df

To summarize, `DataFrame` is like the excel sheet containing multiple columns, and each columns in `DataFrame` is `Series`.

![](https://codetorial.net/pandas/_images/object_creation_01.png)

## 3.3. Reading csv file using Pandas

csv file is the excel file, which is easy to read and write using Python (Pandas). You can read the contents in csv file and create it as the `DataFrame` using Pandas.

For the rest of the tutorial, we will use the csv file named `titanic.csv`. You have to place it in the same directory with this `.ipynb` file. (ex. If this `lab_3.ipynb` file is located in `C:/Documents`, `titanic.csv` should also be in `C:/Documents` too.)

Then, we can read the csv file like follows:

In [ ]:
df = pd.read_csv("titanic.csv")

In [ ]:
df

There are 12 columns. If we want to set the `PassengerId` column as the index of `DataFrame`, we can use `index_col` like follows:

In [ ]:
df = pd.read_csv("titanic.csv", index_col=0)

In [ ]:
df

`index_col=0` means that we will set the first (always remember. In Python, 0 is the first) column as `index` of `DataFrame`.

We can check the `index` using `.index`

In [ ]:
df.index

## 3.4. Viewing Data

We will learn about various methods of viewing data in `Pandas` data structures.

### 3.4.1. df.head() and df.tail()

To view the top and bottoms rows of the dataframe, we can use `df.head()` and `df.tail()`, respectively.

In [ ]:
df.head()

In [ ]:
df.tail()

If we want to see top 3 rows, we can use `df.head(3)`

In [ ]:
df.head(3)

### 3.4.2. df.index and df.columns

We can check the index and column names using `df.index` and `df.columns`.

In [ ]:
df.index

In [ ]:
df.columns

### 3.4.3. df.to_numpy()

`Numpy` and `Pandas` are very compatible libraries. We can change `DataFrame` datatype to `Numpy array` datatype using `df.to_numpy()`.

In [ ]:
df.to_numpy()

### 3.4.4. df.describe()

`df.describe` shows a quick statistic summary of data. (only numerical columns)

In [ ]:
df.describe()